Hash is nil for some reason
```
Error:
DataStorageServerTest#test_put:
NoMethodError: undefined method `each' for nil:NilClass
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:425:in `initialize'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:418:in `new'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:418:in `[]'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/mock.rb:234:in `parse_cookies_from_header'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/mock.rb:187:in `initialize'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `new'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:31:in `request'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
    /Users/dahal/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:74:in `put'
    test.rb:13:in `test_put'
```